name       : python-requests-oauthlib
version    : 1.3.0
release    : 5
source     :
    - https://github.com/requests/requests-oauthlib/archive/v1.3.0.tar.gz : dd42e7ef02f4ed4c24909318670f2c2fb7c1f77c98df75964be5b848a3fb01c3
license    : ISC
component  : programming.python
summary    : OAuthlib support for Python-Requests
description: |
    This project provides first-class OAuth library support for python-requests.
builddeps  :
    - python-mock
    - python-oauthlib
    - python-pyjwt
    - python-pytest
    - python-requests
    - python-requests-mock
rundeps    :
    - python-oauthlib
    - python-requests
build      : |
    %python3_setup
install    : |
    %python3_install
#check      : |
    # Skipped tests require networking
#    %python3_test py.test3 -k 'not testCanPostBinaryData and not test_content_type_override and not test_url_is_native_str'
