name       : python-requests-oauthlib
version    : 1.0.0
release    : 3
source     :
    - https://github.com/requests/requests-oauthlib/archive/v1.0.0.tar.gz : 5859b184f179370a4ee1812ceb0bf89552a444226523f82fb8c9fe52d6a0573b
license    : ISC
component  : programming.python
summary    : OAuthlib support for Python-Requests
description: |
    This project provides first-class OAuth library support for python-requests.
builddeps  :
    - python-mock
    - python-oauthlib
    - python-pyjwt
    - python-pytest
    - python-requests
    - python-requests-mock
    - python-setuptools
rundeps    :
    - python-oauthlib
    - python-requests
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
check      : |
    # Skipped tests require networking
    %python_test py.test -k 'not testCanPostBinaryData and not test_content_type_override and not test_url_is_native_str'
    %python3_test py.test3 -k 'not testCanPostBinaryData and not test_content_type_override and not test_url_is_native_str'
